# Generated by Django 4.0.4 on 2023-12-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_review_tags_project_tags_alter_tag_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='voteratio',
        ),
        migrations.RemoveField(
            model_name='review',
            name='votetotal',
        ),
        migrations.AddField(
            model_name='project',
            name='voteratio',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='votetotal',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
